//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WypozyczalniaJachtow.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Jachty
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Jachty()
        {
            this.Rezerwacja = new HashSet<Rezerwacja>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Zdjecie { get; set; }
        public string Port { get; set; }
        public Nullable<int> IloscMiejsc { get; set; }
        public Nullable<decimal> Dlugosc { get; set; }
        public Nullable<decimal> Szerokosc { get; set; }
        public string Silnik { get; set; }
        public Nullable<int> koszt { get; set; }
        public string Wyposazenie { get; set; }
        public string TypJachtu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rezerwacja> Rezerwacja { get; set; }
    }
}
