//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WypozyczalniaJachtow.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rezerwacja
    {
        public int ID { get; set; }
        public Nullable<int> JachtID { get; set; }
        public string Imie { get; set; }
        public string NrTel { get; set; }
        public Nullable<System.DateTime> DataOd { get; set; }
        public Nullable<System.DateTime> DataDo { get; set; }
        public Nullable<bool> Zaliczka { get; set; }
    
        public virtual Jachty Jachty { get; set; }
    }
}
